### ISSUE TITLE
PT Swap Acceptance: No Output for Hot Chains

### ISSUE THREAD

**Issue by AaronDJohnson** [nanograv/PTMCMCSampler#47]
Currently, the sampler is not writing parallel tempering swap acceptance rates for hot chains. These values are 1.0 for all hot chains. The expected behavior is to have some swaps occur and have acceptance rates output with values < 1.0 for all chains besides the hottest one.

**Comment by AaronDJohnson** [comment]
Fixed by #48

**Comment by vhaasteren** [comment]
Fixed by #48
